### ISSUE TITLE
Socket activation support

### ISSUE THREAD

**Issue by omajid** [tmds/Tmds.Systemd#1]
See https://stackoverflow.com/questions/46284108/linux-net-core-receive-passed-in-socket and http://0pointer.de/blog/projects/socket-activation.html

**Comment by tmds** [comment]
Implemented in https://github.com/tmds/Tmds.Systemd/pull/2
Thanks @omajid for bringing the use-case :)

**Comment by omajid** [comment]
Thanks for the quick fix!
