### ISSUE TITLE
Potential GCHandle leak in Journal.Log

### ISSUE THREAD

**Issue by jkotas** [tmds/Tmds.Systemd#35]
https://github.com/tmds/Tmds.Systemd/blob/604064bb1ae0a632061fcb938b4bad47f3e8bfe9/src/Tmds.Systemd/Journal.cs#L193

This should be in finally block and it should only free the handles that were actually allocated.

**Comment by tmds** [comment]
Thanks for reporting the issue!
This is fixed in 0.6.1 release.
