### ISSUE TITLE
Journal.SyslogIdentifier should default to the application name

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.Systemd#38]
Currently this is hard-coded to "dotnet".

It would be better to match the [systemd.exec](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) behavior:

> If not set, defaults to the process name of the executed process.

**Comment by ygoe** [comment]
Somehow this doesn't do what I'd think it should do. All my messages have "null" as their identifier. When I set the name in the config options manually, it will be used.

**Comment by ygoe** [comment]
Hm, seems to be a problem of my log viewer. It's not "null" but unset. journalctl shows "dotnet" but it's not the same as for console output. Those have the name of the starting script, or whatever I set as `[SyslogIdentifier](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#SyslogIdentifier=)` in the service unit file. But then again, it seems expected that this identifier only applies to console output, not native journal messages.

So I guess I'll have to set this field to a meaningful value in my application. I'll probably fetch it from the app's configuration.
