### ISSUE TITLE
Support for formatted scope message logging

### ISSUE THREAD

**Issue by onyxmaster** [tmds/Tmds.Systemd#48]
Hi!

Currently, the formatted scopes (ones that are created with `ILogger.BeginScope("value: {Value}", 74)`) have only formatting arguments traced as the elements of the message state, because of [this check](https://github.com/tmds/Tmds.Systemd/blob/a92be46121808b450278e0f1414795cc27ed0744/src/Tmds.Systemd.Logging/JournalLogger.cs#L142).
I believe that the full formatted scope message (in the example case "value: 74") should be traced as `SCOPE` state element, as it is done with non-formatted cases like `ILogger.BeginScope("scope A")`. Discovering that converting a scope from a plain string to a formatted one and losing the message itself in the logs is a less-than-pleasant surprise 😂

I've got a repro and willing to assist you with this issue if needed.

**Comment by tmds** [comment]
Yes, also for formatted scope messages, we should add a message field.

Can you make a PR to fix this?

**Comment by onyxmaster** [comment]
I'll try to take a look at it this week or the next one.

**Comment by tmds** [comment]
Great! Thank you.

**Comment by onyxmaster** [comment]
> Yes, also for formatted scope messages, we should add a message field.

I reread this and unsure that I understand the "also" part. Could you clarify a bit? Do you propose "prefixing" the message being logged with scope description one like `ConsoleLogger` does when `IncludeScopes` is enabled?

**Comment by tmds** [comment]
> I reread this and unsure that I understand the "also" part. Could you clarify a bit? Do you propose "prefixing" the message being logged with scope description, like ConsoleLogger does when IncludeScopes is enabled?

I'd keep it in a separate field, like with the non-formatted scopes. wdyt?

**Comment by onyxmaster** [comment]
@tmds, thanks for merging this in. Any chances we can get a 0.7.1 released? I would very much like to upgrade our projects (like [ocsp-responder](https://github.com/drivenet/ocsp-responder), [synchronizzer](https://github.com/drivenet/synchronizzer), [awskms-pkcs11](https://github.com/drivenet/awskms-pkcs11) and a bunch of others) to include the improved scope logging.
