### ISSUE TITLE
A possibility of a fresh release

### ISSUE THREAD

**Issue by onyxmaster** [tmds/Tmds.Systemd#50]
Hi!

Any chances for a 0.7.1 release with the latest bits? I'm (selfishly) very much interested In #49. I understand that I can build the package myself, but I do not want to pollute the Nuget store with unsupported one-off private builds.

Thank you.

**Comment by tmds** [comment]
I want to give some time still for this PR to get finished: https://github.com/tmds/Tmds.Systemd/pull/46. I'll make a release at the end of this week.

**Comment by onyxmaster** [comment]
I'm perfectly OK (not that it's my business, but still) with postponing the release to include the improvement you mentioned, it looks very useful.

**Comment by tmds** [comment]
Just uploaded 0.8.0 to nuget.org.
